# TODO: Definir configuraci√≥n del kernel IPA (microkernel)
# Selecciona los plugins por nombre una vez implementados.
version: 1
preprocessor:
  name: basic
backend:
  name: allosaurus
  params:
    lang: es
textref:
  name: espeak
  params:
    default_lang: es
comparator:
  name: levenshtein
options:
  lang: es
